{
  "name": "oss",
  "host": "0.0.0.0",
  "port": 9502,
  "tags":["oss", "web"],
  "oss":{
    "key":"LTAI5tGH3YwADGhBCyB3Cg3s",
    "secrect":"db9ieC5otI7oye6XlqGr2xPRQfe7sC",
    "host":"https://qvbilam.oss-cn-hangzhou.aliyuncs.com",
    "callback_url":"http://dzyabp.natappfree.cc",
    "upload_dir":"user-images/",
    "expire_time": 300
  }
}