name: "public-web-server"
port: 9501
tags: ["public", "web"]
oss:
  key: "LTAI5tGH3YwADGhBCyB3Cg3s"
  secrect: "db9ieC5otI7oye6XlqGr2xPRQfe7sC"
  host: "https://qvbilam.oss-cn-hangzhou.aliyuncs.com"
  callback_url: "http://qrei2f.natappfree.cc/v1/callback"
  upload_dir: "user-images/"
  expire_time: 300

user-server:
  host: "127.0.0.1"
  port: 9801
  name: "grpc-user-server"
file-server:
  host: "127.0.0.1"
  port: 9803
  name: "grpc-video-server"