apiVersion: apps/v1
kind: Deployment
metadata:
  name: public-web
  labels:
    app: public-web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: public-web
  template:
    metadata:
      labels:
        app: public-web
        version: v1.0
    spec:
      containers:
        - name: public-web
          image: registry.cn-hangzhou.aliyuncs.com/qvbilam/web-server-public:1.0.0
          imagePullPolicy: Always
          ports: # 容器内部使用端口
            - containerPort: 9501
          env:
            # 服务配置
            - name: SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  key: server_name
                  name: public-web
            # oss
            - name: OSS_KEY
              valueFrom:
                secretKeyRef:
                  key: oss_key
                  name: public-web
            - name: OSS_SECRET
              valueFrom:
                secretKeyRef:
                  key: oss_secret
                  name: public-web
            - name: OSS_HOST
              valueFrom:
                secretKeyRef:
                  key: oss_host
                  name: public-web
            - name: OSS_CALLBACK_URL
              valueFrom:
                secretKeyRef:
                  key: oss_callback_url
                  name: public-web
            - name: OSS_UPLOAD_DIR
              valueFrom:
                secretKeyRef:
                  key: oss_upload_dir
                  name: public-web
            - name: OSS_EXPIRE_TIME
              valueFrom:
                secretKeyRef:
                  key: oss_expire_time
                  name: public-web

            # user-server
            - name: USER_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  key: user_server_host
                  name: public-web
            - name: USER_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: user_server_port
                  name: public-web
            - name: USER_SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  key: user_server_name
                  name: public-web
            # public-server
            - name: PUBLIC_SERVER_HOST
              valueFrom:
                configMapKeyRef:
                  key: public_server_host
                  name: public-web
            - name: PUBLIC_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  key: public_server_port
                  name: public-web
            - name: PUBLIC_SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  key: public_server_name
                  name: public-web
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
      imagePullSecrets:
        - name: ali-image-key