apiVersion: "v1"
kind: ConfigMap
metadata:
  name: public-web
  labels:
    app: public-web
data:
  # 服务配置
  server_name: "public-web"
  server_host: "0.0.0.0"

  # user-server
  user_server_name: "user-server"
  user_server_host: "user-server"
  user_server_port: "9801"
  # public-server
  public_server_name: "public-server"
  public_server_host: "public-server"
  public_server_port: "9803"
