apiVersion: v1
kind: Service
metadata:
  name: public-web-server
  labels:
    app: qvbilam-http
spec:
  selector:
    app: public-web
  ports:
    - name: http-server-public
      protocol: TCP
      port: 9703
      targetPort: 9501
  type: NodePort