### 上传视频
POST http://127.0.0.1:9501/v1/video/upload/certificate
Content-Type: application/json

{
  "file_name": "tmd.mp4",
  "file_sha1": "1231241231",
  "file_type": "video/mp4"
}

### 上传视频回调
POST http://127.0.0.1:9501/v1/callback/vod?test=1&demo=callback
Authorization: 123
Content-Type: application/json

{
  "name": "QvBiLam",
  "avatar": "https://www.baodu.com"
}

### 获取视频播放凭证
GET http://127.0.0.1:9501/v1/video/1/play/certificate
